class_name SpecialTile 
extends Node2D

var activated
var current_effect
enum {FIREHYDRANT_HEALTHY,SEWER_HEALTHY, SIGNPOST_HEALTHY, FLAG_DOWN, FIREHYDRANT_BROKEN, SEWER_BROKEN, SIGNPOST_BROKEN, FLAG_UP}
export(int, "FIREHYDRANT_HEALTHY","SEWER_HEALTHY", "SIGNPOST_HEALTHY", "FLAG_DOWN","FIREHYDRANT_BROKEN", "SEWER_BROKEN", "SIGNPOST_BROKEN","FLAG_UP") var current_frame

func _init():
	pass

